# Generated by Django 3.1.7 on 2021-08-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_company_bcc_email"),
        ("users", "0002_auto_20210217_0502"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="companies",
            field=models.ManyToManyField(
                null=True, related_name="users", to="companies.Company", verbose_name="Companies"
            ),
        ),
    ]
