# Generated by Django 3.2.12 on 2022-09-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210817_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clients',
        ),
    ]
