# Generated by Django 3.0.11 on 2021-01-22 16:41

import colorfield.fields
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import localflavor.generic.models
import model_utils.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Company name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='Postal code')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Web site')),
                ('vat_id', models.CharField(blank=True, max_length=20, verbose_name='VAT ID')),
                ('bank', models.TextField(blank=True, verbose_name='Bank')),
                ('bic', localflavor.generic.models.BICField(blank=True, max_length=11, verbose_name='BIC')),
                ('iban', localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=34, use_nordea_extensions=False, verbose_name='IBAN')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('contrast_color', colorfield.fields.ColorField(default='#3B4451', max_length=18, verbose_name='Contrast color')),
                ('signature_text', models.CharField(blank=True, max_length=100, verbose_name='Signature as text')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Signature as image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
