# Generated by Django 3.1.7 on 2021-08-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_thanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_for_bank',
            field=models.CharField(blank=True, max_length=255, verbose_name='name_for_bank'),
        ),
    ]
