# Generated by Django 3.2.10 on 2022-02-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0015_alter_client_slug"),
        ("companies", "0008_company_name_for_bank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyclient",
            options={
                "ordering": ("company", "client"),
                "verbose_name": "Company client",
                "verbose_name_plural": "Company clients",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="override_default_from_email",
            field=models.BooleanField(default=False, verbose_name="Override default from email"),
        ),
        migrations.AlterUniqueTogether(
            name="companyclient",
            unique_together={("client", "company")},
        ),
    ]
