# Generated by Django 3.2.12 on 2022-07-26 19:38

import django.db.models.deletion
from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0017_client_companies"),
        ("companies", "0009_auto_20220202_1016"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="additional_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                verbose_name="Additional phone number",
            ),
        ),
        migrations.AlterField(
            model_name="companyclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clients.client"
            ),
        ),
        migrations.AlterField(
            model_name="companyclient",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.company"
            ),
        ),
    ]
