# Generated by Django 3.2.12 on 2022-07-01 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_client_companies'),
        ('companies', '0009_auto_20220202_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
