# Generated by Django 3.2.12 on 2022-07-26 19:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_invoice_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='invoice_note',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Displayed between banking details and signature', verbose_name='Notes'),
        ),
    ]
