# Generated by Django 3.2.12 on 2022-09-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_auto_20220917_2219'),
        ('companies', '0012_alter_company_invoice_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyClient',
        ),
    ]
