# Generated by Django 3.2.12 on 2022-11-15 10:21

import django.utils.timezone
from django.db import migrations, models

import django_countries.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0013_delete_companyclient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Bank name")),
                ("code", models.IntegerField(null=True, verbose_name="Code")),
                ("swift", models.CharField(blank=True, max_length=11, verbose_name="BIC/Swift")),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "zip_code",
                    models.CharField(blank=True, max_length=10, verbose_name="Postal code"),
                ),
                ("city", models.CharField(blank=True, max_length=255, verbose_name="City")),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True, verbose_name="Country"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank",
                "verbose_name_plural": "Banks",
                "ordering": ("name", "created"),
            },
        ),
    ]
