# Generated by Django 3.2.12 on 2023-03-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_for_bank',
            field=models.CharField(blank=True, max_length=255, verbose_name="Bank account's owner name"),
        ),
    ]
