# Generated by Django 3.2.18 on 2023-05-26 14:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_auto_20230314_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_vat',
            field=models.BooleanField(default=True, verbose_name='Enable VAT'),
        ),
        migrations.AddField(
            model_name='company',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.077'), max_digits=6, verbose_name='VAT rate'),
        ),
        migrations.AlterField(
            model_name='company',
            name='from_email',
            field=models.CharField(blank=True, default='Gregory Favre <greg@beyondthewall.ch>', max_length=255, verbose_name='From email'),
        ),
    ]
