# Generated by Django 3.2.18 on 2023-07-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_auto_20230526_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='from_email',
            field=models.CharField(blank=True, max_length=255, verbose_name='From email'),
        ),
    ]
