# Generated by Django 3.2.18 on 2023-07-04 07:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_alter_company_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Hourly rate'),
        ),
    ]
