# Generated by Django 3.2.18 on 2023-07-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_company_default_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_delay_days',
            field=models.IntegerField(default=30, help_text='Default delay in days to due date', verbose_name='Payment delay'),
        ),
    ]
