exclude: '^docs/|/migrations/'
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: detect-private-key
      - id: fix-encoding-pragma
        args: [ "--remove" ]
      - id: mixed-line-ending
        args: [ "--fix=lf" ]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.13.0"
    hooks:
      - id: django-upgrade
        args: ["--target-version", "4.1"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [ --line-length=99 ]


  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ "--profile", "black", "--line-length", "99"]


  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [ '--max-cognitive-complexity=22' ]
        additional_dependencies:
          - flake8-bugbear
          # - flake8-class-attributes-order
          - flake8-cognitive-complexity
          - flake8-implicit-str-concat
          - flake8-comprehensions
          - flake8-return
          # - flake8-spellcheck
          # - pep8-naming
          # - flake8-variables-names

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
