# Generated by Django 3.0.11 on 2021-01-20 20:51

import uuid

import django.utils.timezone
from django.db import migrations, models

import django_countries.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=10)),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "zip_code",
                    models.CharField(blank=True, max_length=10, verbose_name="Postal code"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=255, verbose_name="City"),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True, verbose_name="Country"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
