# Generated by Django 3.1.6 on 2021-02-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210122_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment_delay_days',
            field=models.IntegerField(default=30, help_text='Default delay in days to due date', verbose_name='Payment delay'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='currency',
            field=models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'Euro')], default='CHF', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano')], default='fr', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.CharField(max_length=10, verbose_name='Slug'),
        ),
    ]
