# Generated by Django 3.1.6 on 2021-02-17 04:24

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20210217_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.077'), max_digits=6, verbose_name='VAT rate'),
        ),
    ]
