# Generated by Django 3.1.7 on 2021-06-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0009_auto_20210426_1759"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ("name", "country")},
        ),
    ]
