# Generated by Django 3.1.7 on 2021-08-13 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_bcc_email'),
        ('clients', '0010_auto_20210607_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company', verbose_name='Company'),
        ),
    ]
