# Generated by Django 3.1.7 on 2021-08-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_client_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="company",
        ),
    ]
