# Generated by Django 3.1.7 on 2021-08-25 06:54

from django.db import migrations

import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0013_auto_20210821_1503"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                default="CH",
                max_length=2,
                null=True,
                verbose_name="Country",
            ),
        ),
    ]
