# Generated by Django 3.2.10 on 2022-02-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20210825_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.CharField(help_text='Used to generate invoice code', max_length=15, verbose_name='Slug'),
        ),
    ]
