# Generated by Django 3.2.12 on 2022-07-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20220202_1016'),
        ('clients', '0016_client_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='companies',
            field=models.ManyToManyField(through='companies.CompanyClient', to='companies.Company', verbose_name='Companies'),
        ),
    ]
