# Generated by Django 3.2.12 on 2022-09-17 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_company_invoice_note'),
        ('clients', '0017_client_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='companies.company', verbose_name='Company'),
        ),
    ]
