# Generated by Django 3.2.12 on 2022-09-17 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_alter_company_invoice_note"),
        ("clients", "0019_dm_client_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="companies",
        ),
        migrations.AlterField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
    ]
