# Generated by Django 3.2.12 on 2023-03-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_auto_20220917_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.CharField(blank=True, help_text='Used to generate invoice code', max_length=15, verbose_name='Slug'),
        ),
    ]
