# Generated by Django 3.0.11 on 2021-01-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20210121_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='expiration',
            new_name='due_date',
        ),
    ]
