# Generated by Django 3.1.6 on 2021-02-17 04:02

import django.db.models.deletion
from django.db import migrations, models

import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_auto_20210122_1750"),
        ("clients", "0003_auto_20210122_1750"),
        ("invoices", "0007_auto_20210215_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="clients.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="code",
            field=models.CharField(blank=True, editable=False, max_length=13, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="displayed_date",
            field=models.DateField(blank=True, null=True, verbose_name="Displayed date"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(null=True, verbose_name="Due date"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="period_end",
            field=models.DateField(blank=True, null=True, verbose_name="End of invoice period"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="period_start",
            field=models.DateField(blank=True, null=True, verbose_name="Start of invoice period"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="qr_bill",
            field=models.TextField(blank=True, null=True, verbose_name="QR Bill"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="title",
            field=models.CharField(blank=True, max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=6,
                verbose_name="Total",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="vat_rate",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0.065, max_digits=6, verbose_name="VAT rate"
            ),
        ),
    ]
