# Generated by Django 3.1.7 on 2021-04-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_auto_20210225_0535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('displayed_date',)},
        ),
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'ordering': ('created',)},
        ),
    ]
