# Generated by Django 3.1.7 on 2021-06-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0014_auto_20210607_1649"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="code",
            field=models.CharField(blank=True, max_length=30, verbose_name="Code"),
        ),
    ]
