# Generated by Django 3.1.7 on 2021-06-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_auto_20210607_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('due_date',)},
        ),
    ]
