# Generated by Django 3.1.7 on 2021-08-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_auto_20210609_0614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-due_date',)},
        ),
    ]
