# Generated by Django 3.2.12 on 2022-03-15 04:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_add_reminder_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePDF',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('error', 'Error')], default='generating', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf', models.FileField(editable=False, null=True, upload_to='invoices/', verbose_name='PDF')),
                ('version', models.PositiveIntegerField(editable=False, null=True, verbose_name='Version of PDF')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', related_name='pdfs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
