# Generated by Django 3.2.12 on 2022-03-15 04:45

from django.db import migrations


def create_dm_pdf(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Invoice = apps.get_model("invoices", "Invoice")
    InvoicePDF = apps.get_model("invoices", "InvoicePDF")
    for invoice in Invoice.objects.all():
        InvoicePDF.objects.create(
            invoice=invoice, pdf=invoice.pdf, version=invoice.pdf_version, status="ready"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0019_invoicepdf"),
    ]

    operations = [
        migrations.RunPython(create_dm_pdf, reverse_code=migrations.RunPython.noop),
    ]
