# Generated by Django 3.2.12 on 2022-03-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0020_dm_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="pdf",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="pdf_version",
        ),
    ]
