# Generated by Django 3.2.12 on 2022-03-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0021_remove_pdf_from_invoice"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invoicepdf",
            unique_together={("invoice", "version")},
        ),
    ]
